#!/bin/bash
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jupyter-matplotlib
conda config --append channels conda-forge
conda config --append channels cta-observatory

conda install ctools